#!/bin/bash
# Non-empty defaults should be set in server-env
. `dirname $0`/server_env

exec ${ERL_DIR}erl \
    ${EBIN_ARGS} \
    -noinput \
    -setcookie $COOKIE \
    -name serverctl@$IP \
    -boot start_clean \
    -s server_control_main \
    -nodename $NODENAME \
    -extra "$@"
