#!/bin/bash
. `dirname $0`/server_env

CONFIG_ARG= #初始化为空
[ -f "${CONFIG_FILE}.config" ] && CONFIG_ARG="-config ${CONFIG_FILE}"

## lager配置
LAGER_CONFIG_ARG= #初始化为空
[ -f "${SCRIPT_DIR}/lager.config" ] && LAGER_CONFIG_ARG="-config ${SCRIPT_DIR}/lager"

START_SERVER=" -s reloader -s main server_start"

# ARGS变量
BASE_ARGS=" -smp $SMP -setcookie $COOKIE +K $POLL +t $ERL_MAX_ATOM +A $THREADS_ASYNC_THREAD +P $ERL_PROCESSES +W w +sbwt none +swt low -boot start_sasl "
NODENAME_ARGS=" -name ${NODENAME}"
MNESIA_ARGS=" -mnesia dump_log_write_threshold 50000 -mnesia dc_dump_limit 64 -mnesia dir \"${MNESIA_DIR}\""

## 注意：\换行后面不可以有空格

## TODO started
help()
{
    echo "./$0 start"  
    echo "./$0 live"
    echo "./$0 stop"
    echo "./$0 backup"
}
case $1 in
    'start') 
        exec ${ERL_DIR}erl ${BASE_ARGS} ${EBIN_ARGS} ${START_SERVER} ${CONFIG_ARG} -noinput -detached \
            ${LAGER_CONFIG_ARG} \
            ${NODENAME_ARGS} ${MNESIA_ARGS} ;;
    'stop')
        `dirname $0`/server_ctl stop;;
    'reload')
        `dirname $0`/server_ctl reload;;
    'backup')
        `dirname $0`/server_ctl backup;;
    'live')
        exec ${ERL_DIR}erl ${BASE_ARGS} ${EBIN_ARGS} ${START_SERVER} ${CONFIG_ARG} \
            ${LAGER_CONFIG_ARG} \
            ${NODENAME_ARGS} ${MNESIA_ARGS} ;;
    'debug')
        ${ERL_DIR}erl  ${BASE_ARGS} -name debug$$_$NODENAME -remsh $NODENAME -hidden ;;
    *)
        help;;
esac











